---
version: '3'

#etworks:
#  nginx-proxy:
#    external:
#      name: frontend-lb
networks:
  web:
    external: true
  db:
    external: true
  zto:
    driver: bridge

services:
  aam-php:
    tty: true
    build:
      context: ./
      dockerfile: ci/dockerfile-phpfpm
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - .:/app

  aam-web:
    image: 'bitnami/nginx:latest'
    depends_on:
      - aam-php
    cap_add:
      - NET_ADMIN
    expose:
      - 80
    ports:
      - '80:8080'
    volumes:
      - ./config/container-nginx.vhost.conf:/opt/bitnami/nginx/conf/vhosts/phpfpm.conf
      - .:/app/
