---
version: '3'

#etworks:
#  nginx-proxy:
#    external:
#      name: frontend-lb
services:
  aam-webapp:
    tty: true
    build:
      context: ./
      dockerfile: ci/dockerfile-phpfpm
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - ./config/container-nginx.vhost.conf:/etc/nginx/conf.d/container-vhost.conf

#  aam-web:
#    image: 'bitnami/nginx:latest'
#    depends_on:
#      - aam-php
#    cap_add:
#      - NET_ADMIN
#    expose:
#      - 80
#    ports:
#      - '80:8080'
#    volumes:
#      - ./config/container-nginx.vhost.conf:/opt/bitnami/nginx/conf/vhosts/phpfpm.conf
#      - .:/app/
