version: '3'

services:
  phpfpm:
    tty: true
    build:
      context: ./
      dockerfile: dockerfile-phpfpm
    #image: 'bitnami/php-fpm:7.3'
    ports:
      - 9000:9000
    volumes:
      - .:/app
  php-composer:
    tty: true
    depends_on:
      - phpfpm
    image: composer:1.8
    command: install
    volumes:
      - .:/app

  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    cap_add:
      - NET_ADMIN
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./config/container-nginx.vhost.conf:/opt/bitnami/nginx/conf/vhosts/phpfpm.conf