version: '3.7'

services:
  deployer:
    tty: true
    user: 82:82
    build:
      dockerfile: ./dockerfile-php-deployer
      context: ./
    command:
        ['sh', '-c', 'pwd && dep -f"ci/deploy.php" --no-ansi ${TASK}']
    volumes:
      - ${SOURCE}:/app
      - ${SSH_KEY}:/home/www-data/.ssh/id_rsa
