version: '3.4'

networks:
  db:
    external: true
  zto:
    driver: bridge 

services:
  migrate:
    tty: true
    build:
      context: ./
      dockerfile: dockerfile-phpfpm
    networks:
        - db
        - zto
    command:
        'php artisan migrate --step --force --database=backendmysql'
    working_dir: '/app'
    volumes:
      - ${SOURCE:-../}:/app
      - ${STORAGE:-../../../shared/storage}:/app/storage

  migrate-status:
    tty: true
    build:
      context: ./
      dockerfile: dockerfile-phpfpm
    networks:
        - db
        - zto
    command:
        'php artisan migrate:status --database=backendmysql'
    working_dir: '/app'
    volumes:
      - ${SOURCE:-../}:/app
      - ${STORAGE:-../../../shared/storage}:/app/storage
